{
    'name': 'Quản lý hóa đơn',
    'version': '1.0',
    'summary': 'Module quản lý hóa đơn phòng khám',
    'sequence': 10,
    'description': """Module quản lý hóa đơn phòng khám""",
    'category': 'Healthcare',
    'author': 'Your Name',
    'website': '',
    'depends': ['base', 'prescription_management', 'website', 'patient_management', 'insurance_management'],
    'data': [
        'security/ir.model.access.csv',
        # 'views/views.xml',
        # 'views/statistics_view.xml',
        # 'views/statistics_wizard_view.xml',
        'views/report_reportlab.xml',
        # 'views/statistics_report.xml',
        'views/layout.xml',
        'views/invoice_templates.xml',
        'views/insurance_templates.xml',
        'views/purchase_templates.xml',
        'views/statistics_templates.xml',
        'views/website_menu.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
